package:
  name: gbdraw
  version: 0.8.0

source:
  path: ../

build:
  number: 0
  noarch: python
  entry_points:
    - gbdraw = gbdraw.cli:main

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
  run:
    - python >=3.10
    - pandas
    - fonttools
    - biopython
    - svgwrite
    - bcbio-gff

test:
  imports:
    - gbdraw
  commands:
    - gbdraw --help
    - gbdraw circular --help
    - gbdraw linear --help

about:
  home: "https://gbdraw.app/" 
  dev_url: "https://github.com/satoshikawato/gbdraw/" 
  doc_url: "https://github.com/satoshikawato/gbdraw/blob/main/docs/DOCS.md"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE.txt"
  summary: "A genome diagram generator for microbes and organelles"
  description: |
    gbdraw is a tool for generating high-quality genome diagrams.
    It supports both circular and linear formats.
    A serverless Web GUI is included and runs locally via `gbdraw gui`.
    Visit https://gbdraw.app/ for the online version.
  fonts_license: "SIL Open Font License (OFL) Version 1.1"

extra:
  recipe-maintainers:
    - satoshikawato
