package:
  name: gbdraw
  version: 0.6.0

source:
  path: ../

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
    - bcbio-gff
  run:
    - python >=3.10
    - pandas
    - fonttools
    - biopython
    - svgwrite
    - cairosvg
    - bcbio-gff

channels:
  - conda-forge
  - bioconda
  - defaults

test:
  imports:
    - gbdraw
  commands:
    - gbdraw --help
    - gbdraw circular --help
    - gbdraw linear --help
    - cairosvg --help

about:
  home: "https://github.com/satoshikawato/gbdraw/"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE.txt"
  summary: "A genome diagram generator for microbes and organelles"
  description: |
    gbdraw is a tool for generating high-quality genome diagrams, supporting both circular and linear formats. 
    It is designed for annotated genomes from microbes and organelles. 
    The web app version is available here: https://gbdraw.streamlit.app/
  fonts_license: "SIL Open Font License (OFL) Version 1.1"
extra:
  recipe-maintainers:
    - satoshikawato
