from setuptools import setup, find_packages

setup(
    name='gbdraw',
    version='0.9.0b0',
    packages=find_packages(),
    install_requires=[
        'pandas',
        'svgwrite',
        'biopython',
        'fonttools',
        'bcbio-gff'
    ],
    extras_require={
        'export': ['cairosvg'],
    },
    package_data={
        'gbdraw': [
            'data/color_palettes.toml', 
            'data/config.toml', 
            'data/*.ttf',
            'web/index.html',
            'web/css/*.css',
            'web/vendor/*.md',
            'web/vendor/*.json',
            'web/vendor/*/*.js',
            'web/vendor/*/*.css',
            'web/vendor/*/*.mjs',
            'web/vendor/*/*.d.ts',
            'web/vendor/*/*.wasm',
            'web/vendor/*/*.zip',
            'web/vendor/*/*.whl',
            'web/vendor/*/*.ttf',
            'web/vendor/*/*.woff',
            'web/vendor/*/*.woff2',
            'web/vendor/*/*.svg',
            'web/vendor/*/*.txt',
            'web/vendor/*/*.md',
            'web/vendor/*/*.whl',
            'web/vendor/*/*/*.js',
            'web/vendor/*/*/*.css',
            'web/vendor/*/*/*.mjs',
            'web/vendor/*/*/*.d.ts',
            'web/vendor/*/*/*.wasm',
            'web/vendor/*/*/*.zip',
            'web/vendor/*/*/*.whl',
            'web/vendor/*/*/*.ttf',
            'web/vendor/*/*/*.woff',
            'web/vendor/*/*/*.woff2',
            'web/vendor/*/*/*.svg',
            'web/vendor/*/*/*.txt',
            'web/vendor/*/*/*.md',
            'web/vendor/*/*/*/*.js',
            'web/vendor/*/*/*/*.css',
            'web/vendor/*/*/*/*.mjs',
            'web/vendor/*/*/*/*.d.ts',
            'web/vendor/*/*/*/*.wasm',
            'web/vendor/*/*/*/*.zip',
            'web/vendor/*/*/*/*.whl',
            'web/vendor/*/*/*/*.json',
            'web/js/*.js',
            'web/js/app/*.js',
            'web/js/app/*/*.js',
            'web/js/services/*.js',
            'web/js/utils/*.js',
            'web/presets/*.txt',
            'web/presets/*.tsv',
            'web/wasm/losat/*.wasm',
            'web/wasm/losat/*.md',
        ]
    },
    include_package_data=True,
    python_requires='>=3.10',
    author='Satoshi Kawato',
    author_email='kawato@kaiyodai.ac.jp',
    description='a genome diagram generator for microbes and organelles',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/satoshikawato/gbdraw/',
    project_urls={
        "Web App": "https://gbdraw.app/",
        "Source": "https://github.com/satoshikawato/gbdraw/",
    },
    entry_points={'console_scripts': ['gbdraw = gbdraw.cli:main',] },
)
