"""Public, stable-ish library API for gbdraw.

This package is the official entry point for pipeline/library usage (as opposed to CLI
entry points). It stays intentionally thin and mostly re-exports internal building
blocks through a stable namespace.
"""

from .canvas import CircularCanvasConfigurator, LinearCanvasConfigurator
from .config import GbdrawConfig, apply_config_overrides, load_default_config
from .configurators import (
    BlastMatchConfigurator,
    DepthConfigurator,
    FeatureDrawingConfigurator,
    GcContentConfigurator,
    GcSkewConfigurator,
    LegendDrawingConfigurator,
)
from .diagram import (  # type: ignore[reportMissingImports]
    DEFAULT_SELECTED_FEATURES,
    assemble_circular_diagram_from_records,
    assemble_circular_diagram_from_record,
    assemble_linear_diagram_from_records,
    build_circular_diagram,
    build_circular_multi_diagram,
    build_linear_diagram,
)
from .io import (
    CircularTrackTable,
    ConservationTable,
    ConservationTableRow,
    RecordsTable,
    RecordsTableRow,
    RegionSpec,
    RecordSelector,
    TablePathDependency,
    apply_region_specs,
    load_gbks,
    load_gff_fasta,
    parse_record_selector,
    parse_record_selectors,
    parse_region_spec,
    parse_region_specs,
    read_circular_track_table,
    read_conservation_table,
    read_label_override_table,
    read_label_whitelist_table,
    read_qualifier_priority_table,
    read_records_table,
)
from gbdraw.analysis.collinearity import (  # type: ignore[reportMissingImports]
    CollinearityAnchor,
    CollinearityBlock,
    CollinearityParameters,
    CollinearityResult,
    CollinearitySearchScope,
    LosslessCollinearityParameters,
    build_orthogroup_collinearity_blocks,
    iter_collinearity_search_pairs,
    normalize_collinearity_search_scope,
)
from gbdraw.analysis.protein_colinearity import (  # type: ignore[reportMissingImports]
    OrthogroupMembershipMode,
    OrthologEdge,
    OrthologPath,
    normalize_orthogroup_membership_mode,
)
from .options import (
    CircularMultiRecordOptions,
    ColorOptions,
    DiagramOptions,
    OutputOptions,
    TrackOptions,
)
from .render import parse_formats, render_to_bytes, save_figure, save_figure_to
from .request_render import (
    PreparedDiagramRequest,
    RequestRenderResult,
    build_request_diagram,
    normalize_request_records,
    render_request,
)
from .requests import (
    CircularDiagramRequest,
    DiagramRequest,
    GenBankInputSource,
    GffFastaInputSource,
    InMemoryRecordSource,
    LinearDiagramRequest,
    RecordInput,
    RecordInputSource,
    RecordPresentation,
    RenderOutputRequest,
)
from gbdraw.render.interactive_context import build_interactive_svg_context
from gbdraw.render.interactive_svg import InteractiveSvgContext, enrich_svg
from gbdraw.session import (
    MaterializedSession,
    SessionConversionError,
    SessionDocument,
    SessionError,
    SessionFormatError,
    SessionRenderError,
    SessionResourceError,
    SessionVersionError,
    build_session_document,
    load_session_document,
    materialize_session,
    render_session,
    save_session_document,
    session_to_request,
    with_request_output,
)
from .tracks import (  # type: ignore[reportMissingImports]
    CircularTrackRendererName,
    CircularTrackSide,
    CircularTrackSlot,
    LinearTrackRendererName,
    LinearTrackSide,
    LinearTrackSlot,
    ScalarSpec,
    SUPPORTED_CIRCULAR_TRACK_RENDERERS,
    SUPPORTED_LINEAR_TRACK_RENDERERS,
    CircularTrackSlotParseError,
    LinearTrackSlotParseError,
    circular_track_slots_with_axis_side,
    circular_track_slots_from_order,
    default_circular_track_slots,
    default_linear_track_slots,
    linear_track_slots_from_order,
    linear_track_slots_with_axis_side,
    normalize_circular_track_slots_with_axis,
    normalize_linear_track_slots_with_axis,
    parse_circular_track_slot,
    parse_circular_track_slots,
    parse_linear_track_slot,
    parse_linear_track_slots,
)

__all__ = [
    # canvas
    "CircularCanvasConfigurator",
    "LinearCanvasConfigurator",
    # config
    "GbdrawConfig",
    "apply_config_overrides",
    "load_default_config",
    # configurators
    "BlastMatchConfigurator",
    "DepthConfigurator",
    "FeatureDrawingConfigurator",
    "GcContentConfigurator",
    "GcSkewConfigurator",
    "LegendDrawingConfigurator",
    # diagrams
    "DEFAULT_SELECTED_FEATURES",
    "assemble_circular_diagram_from_records",
    "assemble_circular_diagram_from_record",
    "assemble_linear_diagram_from_records",
    "build_circular_diagram",
    "build_circular_multi_diagram",
    "build_linear_diagram",
    # io
    "CircularTrackTable",
    "ConservationTable",
    "ConservationTableRow",
    "RecordsTable",
    "RecordsTableRow",
    "RegionSpec",
    "RecordSelector",
    "TablePathDependency",
    "apply_region_specs",
    "load_gbks",
    "load_gff_fasta",
    "parse_record_selector",
    "parse_record_selectors",
    "parse_region_spec",
    "parse_region_specs",
    "read_circular_track_table",
    "read_conservation_table",
    "read_label_override_table",
    "read_label_whitelist_table",
    "read_qualifier_priority_table",
    "read_records_table",
    # collinearity
    "CollinearityAnchor",
    "CollinearityBlock",
    "CollinearityParameters",
    "CollinearityResult",
    "CollinearitySearchScope",
    "LosslessCollinearityParameters",
    "build_orthogroup_collinearity_blocks",
    "iter_collinearity_search_pairs",
    "normalize_collinearity_search_scope",
    "OrthogroupMembershipMode",
    "OrthologEdge",
    "OrthologPath",
    "normalize_orthogroup_membership_mode",
    # options
    "CircularMultiRecordOptions",
    "ColorOptions",
    "DiagramOptions",
    "OutputOptions",
    "TrackOptions",
    # render
    "InteractiveSvgContext",
    "build_interactive_svg_context",
    "enrich_svg",
    "parse_formats",
    "render_to_bytes",
    "save_figure",
    "save_figure_to",
    # typed requests
    "CircularDiagramRequest",
    "DiagramRequest",
    "GenBankInputSource",
    "GffFastaInputSource",
    "InMemoryRecordSource",
    "LinearDiagramRequest",
    "RecordInput",
    "RecordInputSource",
    "RecordPresentation",
    "RenderOutputRequest",
    "PreparedDiagramRequest",
    "RequestRenderResult",
    "build_request_diagram",
    "normalize_request_records",
    "render_request",
    # canonical sessions
    "MaterializedSession",
    "SessionConversionError",
    "SessionDocument",
    "SessionError",
    "SessionFormatError",
    "SessionRenderError",
    "SessionResourceError",
    "SessionVersionError",
    "build_session_document",
    "load_session_document",
    "materialize_session",
    "render_session",
    "save_session_document",
    "session_to_request",
    "with_request_output",
    # tracks (foundation)
    "CircularTrackRendererName",
    "CircularTrackSide",
    "CircularTrackSlot",
    "LinearTrackRendererName",
    "LinearTrackSide",
    "LinearTrackSlot",
    "ScalarSpec",
    "SUPPORTED_CIRCULAR_TRACK_RENDERERS",
    "SUPPORTED_LINEAR_TRACK_RENDERERS",
    "CircularTrackSlotParseError",
    "LinearTrackSlotParseError",
    "circular_track_slots_with_axis_side",
    "circular_track_slots_from_order",
    "default_circular_track_slots",
    "default_linear_track_slots",
    "linear_track_slots_from_order",
    "linear_track_slots_with_axis_side",
    "normalize_circular_track_slots_with_axis",
    "normalize_linear_track_slots_with_axis",
    "parse_circular_track_slot",
    "parse_circular_track_slots",
    "parse_linear_track_slot",
    "parse_linear_track_slots",
]


