#!/usr/bin/env python3
"""Generate the browser's bundled-font metrics for Legend text measurement.

The Web lays out an edited Legend with a port of Python's Legend layout
(``gbdraw/web/js/services/legend-layout.js``). Its text measurement reads the
same font facts that ``gbdraw.core.text.get_text_bbox_size_pixels`` reads, so
this module records them from the bundled fonts with the same expressions:
the cmap, per glyph the advance, left side bearing, ``xMax``, ``yMax`` and
``yMin``, and the kerned glyph pairs of ``font_pair_kerning_table``.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
TARGET = REPO_ROOT / "gbdraw" / "web" / "js" / "utils" / "legend-font-metrics.generated.js"
sys.path.insert(0, str(REPO_ROOT))

from gbdraw.core import text as gbdraw_text  # noqa: E402

# The Legend measures with the default weight and style (calculate_bbox_dimensions
# is called without them), so it reads only the Regular faces. Another face
# costs about 95 KB here.
MEASURED_FACES = (
    "LiberationSans-Regular",
    "LiberationSerif-Regular",
    "LiberationMono-Regular",
)
NUMBERS_PER_LINE = 40


def _bundled_font_paths() -> dict[str, Path]:
    return {
        Path(str(path)).stem: Path(str(path))
        for path in gbdraw_text._available_bundled_fonts()
    }


def _glyph_facts(font, glyph_name: str) -> list[int]:
    # The expressions of get_text_bbox_size_pixels, read once per glyph.
    try:
        glyph = font["glyf"][glyph_name]
        ymax = glyph.yMax if hasattr(glyph, "yMax") else 0
        ymin = glyph.yMin if hasattr(glyph, "yMin") else 0
        xmax = glyph.xMax if hasattr(glyph, "xMax") else 0
    except Exception:
        ymax, ymin, xmax = 0, 0, 0
    try:
        advance, lsb = font["hmtx"][glyph_name]
    except KeyError:
        advance, lsb = 1000, 0
    return [int(advance), int(lsb), int(xmax), int(ymax), int(ymin)]


def _face_payload(name: str, path: Path) -> dict[str, object]:
    font = gbdraw_text._get_cached_font(str(path))
    if font is None:
        raise SystemExit(f"Cannot read bundled font {path}")
    order = font.getGlyphOrder()
    index = {glyph: position for position, glyph in enumerate(order)}
    cmap = font["cmap"].getcmap(3, 1).cmap
    mapped = set(cmap.values())
    # Python's applied pairs (GPOS `kern` feature lookups, else the legacy
    # `kern` table), limited to glyphs a character can reach through the cmap.
    kerning = []
    for (left, right), value in gbdraw_text.font_pair_kerning_table(font).items():
        if value and left in mapped and right in mapped:
            kerning.extend([index[left], index[right], int(value)])
    return {
        "unitsPerEm": int(font["head"].unitsPerEm),
        "cmap": [value for code_point in sorted(cmap) for value in (code_point, index[cmap[code_point]])],
        "glyphs": [value for glyph in order for value in _glyph_facts(font, glyph)],
        "kerning": kerning,
    }


def _wrapped(values: list[int], indent: str) -> str:
    lines = [
        ", ".join(str(value) for value in values[start:start + NUMBERS_PER_LINE])
        for start in range(0, len(values), NUMBERS_PER_LINE)
    ]
    return "[\n" + ",\n".join(f"{indent}  {line}" for line in lines) + f"\n{indent}]"


def render_legend_font_metrics_module() -> str:
    paths = _bundled_font_paths()
    missing = [name for name in MEASURED_FACES if name not in paths]
    if missing:
        raise SystemExit(f"Bundled fonts not found: {', '.join(missing)}")
    faces = []
    for name in MEASURED_FACES:
        face = _face_payload(name, paths[name])
        faces.append(
            f"    {json.dumps(name)}: {{\n"
            f"      unitsPerEm: {face['unitsPerEm']},\n"
            f"      cmap: {_wrapped(face['cmap'], '      ')},\n"
            f"      glyphs: {_wrapped(face['glyphs'], '      ')},\n"
            f"      kerning: {_wrapped(face['kerning'], '      ')}\n"
            "    }"
        )
    aliases = json.dumps(dict(sorted(gbdraw_text._BUNDLED_FONT_FAMILY_ALIASES.items())), indent=2)
    bundled = json.dumps(sorted(paths), indent=2)
    return (
        "// @ts-check\n"
        "// Generated by tools/generate_legend_font_metrics.py; do not edit manually.\n"
        "// The bundled-font facts gbdraw.core.text.get_text_bbox_size_pixels reads, per face:\n"
        "// cmap [code point, glyph, ...], glyphs [advance, lsb, xMax, yMax, yMin, ...] by glyph\n"
        "// index, kerning [left glyph, right glyph, value, ...] from font_pair_kerning_table.\n"
        "\n"
        "/**\n"
        " * @typedef {object} LegendFontFaceTable\n"
        " * @property {number} unitsPerEm\n"
        " * @property {readonly number[]} cmap Flat [code point, glyph index, ...], ascending code points.\n"
        " * @property {readonly number[]} glyphs Flat [advance, lsb, xMax, yMax, yMin, ...] by glyph index, in font units.\n"
        " * @property {readonly number[]} kerning Flat [left glyph, right glyph, value, ...], in font units.\n"
        " */\n"
        "/**\n"
        " * @typedef {object} LegendFontMetricsTable\n"
        " * @property {Readonly<Record<string, string>>} familyAliases Python's _BUNDLED_FONT_FAMILY_ALIASES.\n"
        " * @property {readonly string[]} bundledFaces Every bundled face stem, sorted.\n"
        " * @property {Readonly<Record<string, LegendFontFaceTable>>} faces The measured faces, by stem.\n"
        " */\n"
        "\n"
        "/** @type {LegendFontMetricsTable} */\n"
        "export const LEGEND_FONT_METRICS = Object.freeze({\n"
        f"  familyAliases: Object.freeze({aliases.replace(chr(10), chr(10) + '  ')}),\n"
        f"  bundledFaces: Object.freeze({bundled.replace(chr(10), chr(10) + '  ')}),\n"
        "  faces: Object.freeze({\n"
        + ",\n".join(faces)
        + "\n  })\n"
        "});\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the generated browser font metrics are out of sync.",
    )
    args = parser.parse_args()

    expected = render_legend_font_metrics_module()
    if args.check:
        if not TARGET.is_file() or TARGET.read_text(encoding="utf-8") != expected:
            print(
                "Browser Legend font metrics are stale. "
                "Run: python tools/generate_legend_font_metrics.py"
            )
            return 1
        return 0

    TARGET.write_text(expected, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
