#!/usr/bin/env python3
"""Generate the browser's versioned mode-profile data module."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
TARGET = REPO_ROOT / "gbdraw" / "web" / "js" / "mode-profiles.generated.js"
sys.path.insert(0, str(REPO_ROOT))

from gbdraw.mode_profiles import mode_profiles_payload  # noqa: E402


def render_mode_profiles_module() -> str:
    payload = json.dumps(mode_profiles_payload(), indent=2, sort_keys=True)
    return (
        "// Generated by tools/generate_mode_profiles.py; do not edit manually.\n"
        "\n"
        "const deepFreeze = (value) => {\n"
        "  if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value;\n"
        "  Object.values(value).forEach((entry) => deepFreeze(entry));\n"
        "  return Object.freeze(value);\n"
        "};\n"
        "\n"
        f"export const MODE_PROFILE_DATA = deepFreeze({payload});\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the generated browser profile is out of sync.",
    )
    args = parser.parse_args()

    expected = render_mode_profiles_module()
    if args.check:
        if not TARGET.is_file() or TARGET.read_text(encoding="utf-8") != expected:
            print(
                "Browser mode profiles are stale. "
                "Run: python tools/generate_mode_profiles.py"
            )
            return 1
        return 0

    TARGET.write_text(expected, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
