#!/usr/bin/env python3
"""Generate the browser's mode-scoped settings registry module (Session 46)."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
TARGET = REPO_ROOT / "gbdraw" / "web" / "js" / "mode-scoped-settings.generated.js"
sys.path.insert(0, str(REPO_ROOT))

from gbdraw.web_support.mode_scoped_settings import mode_scoped_settings_payload  # noqa: E402


def _render_payload() -> str:
    # One registry row per line, so a row change is a one-line diff.
    payload = mode_scoped_settings_payload()
    rows = payload.pop("rows")
    fields = [
        f"  {json.dumps(name)}: "
        + json.dumps(value, indent=2, sort_keys=True).replace("\n", "\n  ")
        for name, value in sorted(payload.items())
    ]
    rendered_rows = ",\n".join(
        "    " + json.dumps(row, sort_keys=True, separators=(", ", ": ")) for row in rows
    )
    fields.append(f'  "rows": [\n{rendered_rows}\n  ]')
    return "{\n" + ",\n".join(fields) + "\n}"


def render_mode_scoped_settings_module() -> str:
    payload = _render_payload()
    return (
        "// @ts-check\n"
        "// Generated by tools/generate_mode_scoped_settings.py from\n"
        "// gbdraw/web_support/mode_scoped_settings.py; do not edit manually.\n"
        "\n"
        "const deepFreeze = (value) => {\n"
        "  if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value;\n"
        "  Object.values(value).forEach((entry) => deepFreeze(entry));\n"
        "  return Object.freeze(value);\n"
        "};\n"
        "\n"
        f"export const MODE_SCOPED_SETTINGS = deepFreeze({payload});\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the generated browser registry is out of sync.",
    )
    args = parser.parse_args()

    expected = render_mode_scoped_settings_module()
    if args.check:
        if not TARGET.is_file() or TARGET.read_text(encoding="utf-8") != expected:
            print(
                "Browser mode-scoped settings are stale. "
                "Run: python tools/generate_mode_scoped_settings.py"
            )
            return 1
        return 0

    TARGET.write_text(expected, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
